FROM arm64v8/fedora:40

# Installing https also installs systemd.
RUN dnf -y install passwd procps less vim tree openssh-server systemd iputils openssh-clients iproute  crontabs sudo initscripts selinux-policy && dnf clean all 

# Create SSH User (Ansible User)
RUN /usr/sbin/useradd  ansible-user
RUN echo 'password' | passwd ansible-user --stdin
RUN echo 'ansible-user ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ansible-user


STOPSIGNAL SIGRTMIN+3
EXPOSE 80
EXPOSE 443
EXPOSE 22

CMD [ "/sbin/init" ]
