FROM registry.redhat.io/rhel9/rhel-bootc:9.4

ARG UN
ARG PW


# Installing https also installs systemd
RUN echo "#!/bin/bash" > register.sh
RUN echo "subscription-manager register --username ${UN} --password ${PW} --auto-attach" >> register.sh && chmod +x register.sh
RUN  ./register.sh
RUN dnf -y install passwd procps less vim tree openssh-server systemd iputils openssh-clients iproute python3 crontabs sudo initscripts selinux-policy && dnf clean all 

# Create SSH User (Ansible User)
RUN /usr/sbin/useradd  ansible-user
RUN echo 'password' | passwd ansible-user --stdin
RUN echo 'ansible-user ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ansible-user

#RUN subscription-manager remove --all 
#RUN subscription-manager unregister

STOPSIGNAL SIGRTMIN+3
EXPOSE 80
EXPOSE 443
EXPOSE 22

CMD ["/sbin/init"]
